Repository ssu-student-union/homepage-backend, pull requests merged in 2024-08, with the labels that each got.

#41 [feat] #40 게시판별 좋아요 많은 게시물 api 구현 및 쿼리dsl, common(페이지네이션, p6spy)
  build.gradle
  src/main/generated/ussum/homepage/infra/jpa/post/entity/QPostEntity.java
  src/main/java/ussum/homepage/application/post/controller/PostController.java
  src/main/java/ussum/homepage/application/post/service/PostService.java
  src/main/java/ussum/homepage/application/post/service/dto/response/SimplePostResponse.java
  src/main/java/ussum/homepage/application/post/service/dto/response/TopLikedPostListResponse.java
  src/main/java/ussum/homepage/domain/post/PostRepository.java
  src/main/java/ussum/homepage/domain/post/service/PostReader.java
  src/main/java/ussum/homepage/global/common/CustomP6spySqlFormatter.java
  src/main/java/ussum/homepage/global/common/PageInfo.java
  src/main/java/ussum/homepage/infra/jpa/post/PostMapper.java
  src/main/java/ussum/homepage/infra/jpa/post/PostRepositoryImpl.java
  src/main/java/ussum/homepage/infra/jpa/post/dto/SimplePostDto.java
Labels: feature

#46 [feat] : 게시판 조회 별 dto 반환 로직 구현
  src/main/generated/ussum/homepage/infra/jpa/post/entity/QPostEntity.java
  src/main/java/ussum/homepage/application/post/controller/PostManageController.java
  src/main/java/ussum/homepage/application/post/service/PostManageService.java
  src/main/java/ussum/homepage/application/post/service/dto/request/PostCreateRequest.java
  src/main/java/ussum/homepage/application/post/service/dto/request/PostUpdateRequest.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postList/AuditPostResponseDto.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postList/LostPostResponse.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postList/NoticePostResponse.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postList/PartnerPostResponse.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postList/PetitionPostResponse.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postList/PostListRes.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postList/PostListResDto.java
  src/main/java/ussum/homepage/domain/post/Post.java
  src/main/java/ussum/homepage/domain/post/PostRepository.java
  src/main/java/ussum/homepage/domain/post/service/PostReader.java
  src/main/java/ussum/homepage/domain/postlike/PostReactionRepository.java
  src/main/java/ussum/homepage/domain/postlike/service/PostReactionReader.java
  src/main/java/ussum/homepage/global/error/status/ErrorStatus.java
  src/main/java/ussum/homepage/infra/jpa/post/PostMapper.java
  src/main/java/ussum/homepage/infra/jpa/post/PostRepositoryImpl.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/PostEntity.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/Status.java
  src/main/java/ussum/homepage/infra/jpa/post/repository/PostJpaRepository.java
  src/main/java/ussum/homepage/infra/jpa/postlike/PostReactionRepositoryImpl.java
Labels: feature

#51 [refactor] #44 청원게시물 OnGoingStatus 로직 수정
  src/main/java/ussum/homepage/application/comment/service/CommentService.java
  src/main/java/ussum/homepage/application/post/service/PostManageService.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postDetail/PetitionPostDetailResponse.java
  src/main/java/ussum/homepage/domain/member/MemberRepository.java
  src/main/java/ussum/homepage/domain/member/service/MemberManager.java
  src/main/java/ussum/homepage/domain/member/service/MemberReader.java
  src/main/java/ussum/homepage/domain/post/PostRepository.java
  src/main/java/ussum/homepage/domain/post/service/PostStatusProcessor.java
  src/main/java/ussum/homepage/domain/post/service/formatter/PostDetailFunction.java
  src/main/java/ussum/homepage/global/config/SecurityConfig.java
  src/main/java/ussum/homepage/global/error/status/ErrorStatus.java
  src/main/java/ussum/homepage/infra/jpa/member/MemberRepositoryImpl.java
  src/main/java/ussum/homepage/infra/jpa/post/PostMapper.java
  src/main/java/ussum/homepage/infra/jpa/post/PostRepositoryImpl.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/CategoryCode.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/OngoingStatus.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/PostEntity.java
Labels: refactor

#53 [feat] : #48 Post 생성, 수정, 파일 관련 로직 추가, 자잘한 로직 수정
  src/main/java/ussum/homepage/application/post/controller/PostManageController.java
  src/main/java/ussum/homepage/application/post/service/PostManageService.java
  src/main/java/ussum/homepage/application/post/service/PostService.java
  src/main/java/ussum/homepage/application/post/service/dto/request/PostCreateRequest.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postSave/PostCreateResponse.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postSave/PostFileResponse.java
  src/main/java/ussum/homepage/application/user/service/OnBoardingService.java
  src/main/java/ussum/homepage/domain/post/PostFileRepository.java
  src/main/java/ussum/homepage/domain/post/service/PostAppender.java
  src/main/java/ussum/homepage/domain/post/service/PostFileAppender.java
  src/main/java/ussum/homepage/global/config/SecurityConfig.java
  src/main/java/ussum/homepage/global/error/status/ErrorStatus.java
  src/main/java/ussum/homepage/infra/jpa/post/PostFileMapper.java
  src/main/java/ussum/homepage/infra/jpa/post/PostFileRepositoryImpl.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/PostFileEntity.java
  src/main/java/ussum/homepage/infra/utils/S3utils.java
Labels: feature

#56 [refactor] #52 청원게시물 단건 조회 시 공식답변(댓글) 포함 및 게시물 파일 생성 경로 수정
  src/main/java/ussum/homepage/application/comment/service/CommentService.java
  src/main/java/ussum/homepage/application/comment/service/dto/response/PostOfficialCommentResponse.java
  src/main/java/ussum/homepage/application/post/controller/PostManageController.java
  src/main/java/ussum/homepage/application/post/service/PostManageService.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postDetail/PetitionPostDetailResponse.java
  src/main/java/ussum/homepage/application/user/service/OnBoardingService.java
  src/main/java/ussum/homepage/domain/comment/PostCommentRepository.java
  src/main/java/ussum/homepage/domain/comment/service/PostCommentFormatter.java
  src/main/java/ussum/homepage/domain/comment/service/PostCommentReader.java
  src/main/java/ussum/homepage/domain/comment/service/PostOfficialCommentFormatter.java
  src/main/java/ussum/homepage/domain/comment/service/formatter/PostOfficialCommentFormatter.java
  src/main/java/ussum/homepage/domain/post/service/PostStatusProcessor.java
  src/main/java/ussum/homepage/domain/post/service/formatter/PostDetailFunction.java
  src/main/java/ussum/homepage/global/config/SecurityConfig.java
  src/main/java/ussum/homepage/infra/jpa/comment/PostCommentRepositoryImpl.java
  src/main/java/ussum/homepage/infra/jpa/post/BoardRepositoryImpl.java
Labels: refactor

#57 [feat] : #54 onBoarding 일단 완료
  src/main/generated/ussum/homepage/infra/jpa/comment/entity/QPostCommentEntity.java
  src/main/generated/ussum/homepage/infra/jpa/post/entity/QCategoryEntity.java
  src/main/generated/ussum/homepage/infra/jpa/post/entity/QPostEntity.java
  src/main/generated/ussum/homepage/infra/jpa/post/entity/QPostFileEntity.java
  src/main/generated/ussum/homepage/infra/jpa/user/entity/QGroupEntity.java
  src/main/generated/ussum/homepage/infra/jpa/user/entity/QMemberEntity.java
  src/main/java/ussum/homepage/application/user/service/OnBoardingService.java
  src/main/java/ussum/homepage/application/user/service/dto/request/OnBoardingRequest.java
  src/main/java/ussum/homepage/domain/csv_user/service/StudentCsvReader.java
  src/main/java/ussum/homepage/domain/member/Member.java
  src/main/java/ussum/homepage/domain/member/MemberRepository.java
  src/main/java/ussum/homepage/domain/member/service/MemberAppender.java
  src/main/java/ussum/homepage/domain/user/User.java
  src/main/java/ussum/homepage/domain/user/UserRepository.java
  src/main/java/ussum/homepage/domain/user/service/UserModifier.java
  src/main/java/ussum/homepage/global/config/SecurityConfig.java
  src/main/java/ussum/homepage/infra/jpa/member/MemberMapper.java
  src/main/java/ussum/homepage/infra/jpa/member/MemberRepositoryImpl.java
  src/main/java/ussum/homepage/infra/jpa/member/entity/MajorCode.java
  src/main/java/ussum/homepage/infra/jpa/member/entity/MemberCode.java
  src/main/java/ussum/homepage/infra/jpa/member/entity/MemberEntity.java
  src/main/java/ussum/homepage/infra/jpa/user/UserRepositoryImpl.java
  src/main/java/ussum/homepage/infra/jpa/user/entity/MajorCode.java
Labels: feature

#58 [feat] 온보딩 실패 시 문의 메일 api 추가
  build.gradle
  src/main/java/ussum/homepage/application/user/controller/OnBoardingController.java
  src/main/java/ussum/homepage/application/user/service/OnBoardingService.java
  src/main/java/ussum/homepage/application/user/service/dto/request/OnBoardingEmailRequest.java
  src/main/java/ussum/homepage/domain/user/exception/OnBoardingMessagingException.java
  src/main/java/ussum/homepage/global/config/MailConfig.java
  src/main/java/ussum/homepage/global/error/status/ErrorStatus.java
Labels: feature

#59 [fix] : OnBoarding 관련 메소드 수정
  src/main/java/ussum/homepage/application/user/service/OnBoardingService.java
  src/main/java/ussum/homepage/domain/member/Member.java
  src/main/java/ussum/homepage/domain/member/MemberRepository.java
  src/main/java/ussum/homepage/infra/jpa/member/MemberMapper.java
  src/main/java/ussum/homepage/infra/jpa/member/MemberRepositoryImpl.java
  src/main/java/ussum/homepage/infra/jpa/member/entity/MemberEntity.java
Labels: refactor, fix

#61 [refactor] #55 메일 문의시 바로 회신가능하게 수정
  src/main/java/ussum/homepage/application/user/controller/OnBoardingController.java
  src/main/java/ussum/homepage/application/user/service/OnBoardingService.java
  src/main/java/ussum/homepage/application/user/service/dto/request/OnBoardingEmailRequest.java
Labels: refactor

#60 [feat] #50 자료집 리스트 api 구현
  src/main/generated/ussum/homepage/infra/jpa/comment/entity/QPostReplyCommentEntity.java
  src/main/generated/ussum/homepage/infra/jpa/group/entity/QGroupEntity.java
  src/main/generated/ussum/homepage/infra/jpa/member/entity/QMemberEntity.java
  src/main/generated/ussum/homepage/infra/jpa/post/entity/QPostFileEntity.java
  src/main/generated/ussum/homepage/infra/jpa/reaction/entity/QPostReplyCommentReactionEntity.java
  src/main/java/ussum/homepage/application/post/controller/PostManageController.java
  src/main/java/ussum/homepage/application/post/service/PostManageService.java
  src/main/java/ussum/homepage/application/post/service/dto/response/DataPostResponse.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postList/LostPostResponse.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postList/NoticePostResponse.java
  src/main/java/ussum/homepage/domain/post/PostFile.java
  src/main/java/ussum/homepage/domain/post/PostRepository.java
  src/main/java/ussum/homepage/domain/post/service/PostReader.java
  src/main/java/ussum/homepage/infra/jpa/group/GroupMapper.java
  src/main/java/ussum/homepage/infra/jpa/member/entity/MemberEntity.java
  src/main/java/ussum/homepage/infra/jpa/post/PostFileMapper.java
  src/main/java/ussum/homepage/infra/jpa/post/PostRepositoryImpl.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/PostFileEntity.java
Labels: feature

#64 [refactor] #63 categoryEntity 삭제 및 postEntity에 category 필드 추가, category관련 코드 삭제
  src/main/generated/ussum/homepage/infra/jpa/post/entity/QCategoryEntity.java
  src/main/generated/ussum/homepage/infra/jpa/post/entity/QPostEntity.java
  src/main/generated/ussum/homepage/infra/jpa/post/entity/QPostFileEntity.java
  src/main/java/ussum/homepage/application/post/controller/PostController.java
  src/main/java/ussum/homepage/application/post/controller/PostManageController.java
  src/main/java/ussum/homepage/application/post/service/PostManageService.java
  src/main/java/ussum/homepage/application/post/service/PostService.java
  src/main/java/ussum/homepage/application/post/service/dto/request/PostCreateRequest.java
  src/main/java/ussum/homepage/application/post/service/dto/request/PostSearchRequest.java
  src/main/java/ussum/homepage/application/post/service/dto/request/PostUpdateRequest.java
  src/main/java/ussum/homepage/application/post/service/dto/response/CategoryResponse.java
  src/main/java/ussum/homepage/application/post/service/dto/response/PostListResponse.java
  src/main/java/ussum/homepage/application/post/service/dto/response/PostResponse.java
  src/main/java/ussum/homepage/application/reaction/controller/PostReactionController.java
  src/main/java/ussum/homepage/application/reaction/service/PostReactionService.java
  src/main/java/ussum/homepage/application/reaction/service/dto/response/PostReactionRes.java
  src/main/java/ussum/homepage/application/reaction/service/dto/response/PostReactionResponse.java
  src/main/java/ussum/homepage/domain/comment/service/formatter/PostCommentFormatter.java
  src/main/java/ussum/homepage/domain/post/Category.java
  src/main/java/ussum/homepage/domain/post/CategoryRepository.java
  src/main/java/ussum/homepage/domain/post/Post.java
  src/main/java/ussum/homepage/domain/post/PostRepository.java
  src/main/java/ussum/homepage/domain/post/service/CategoryFormatter.java
  src/main/java/ussum/homepage/domain/post/service/CategoryReader.java
  src/main/java/ussum/homepage/domain/post/service/PostFormatter.java
  src/main/java/ussum/homepage/domain/post/service/PostModifier.java
  src/main/java/ussum/homepage/domain/post/service/PostStatusProcessor.java
  src/main/java/ussum/homepage/domain/post/service/formatter/CategoryFormatter.java
  src/main/java/ussum/homepage/domain/post/service/formatter/PostFormatter.java
  src/main/java/ussum/homepage/domain/postlike/service/PostReactionFormatter.java
  src/main/java/ussum/homepage/domain/postlike/service/formatter/PostReactionFormatter.java
  src/main/java/ussum/homepage/domain/reaction/service/formatter/PostCommentReactionFormatter.java
  src/main/java/ussum/homepage/global/config/SecurityConfig.java
  src/main/java/ussum/homepage/infra/jpa/post/CategoryMapper.java
  src/main/java/ussum/homepage/infra/jpa/post/CategoryRepositoryImpl.java
  src/main/java/ussum/homepage/infra/jpa/post/PostMapper.java
  src/main/java/ussum/homepage/infra/jpa/post/PostRepositoryImpl.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/Category.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/CategoryEntity.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/PostEntity.java
  src/main/java/ussum/homepage/infra/jpa/post/repository/CategoryJpaRepository.java
  src/main/java/ussum/homepage/infra/jpa/post/repository/PostJpaRepository.java
Labels: refactor

#68 [fix] #67 BoardFactory id null 문제 해결
  src/main/java/ussum/homepage/application/comment/controller/CommentController.java
  src/main/java/ussum/homepage/application/comment/controller/PostCommentManagerController.java
  src/main/java/ussum/homepage/application/comment/controller/PostReplyCommentController.java
  src/main/java/ussum/homepage/application/post/controller/PostController.java
  src/main/java/ussum/homepage/application/post/controller/PostManageController.java
  src/main/java/ussum/homepage/application/post/service/PostManageService.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postDetail/PetitionPostDetailResponse.java
  src/main/java/ussum/homepage/application/reaction/controller/PostCommentReactionController.java
  src/main/java/ussum/homepage/application/reaction/controller/PostReactionController.java
  src/main/java/ussum/homepage/application/reaction/controller/PostReplyCommentReactionController.java
  src/main/java/ussum/homepage/domain/post/service/PostStatusProcessor.java
  src/main/java/ussum/homepage/domain/post/service/factory/BoardFactory.java
  src/main/java/ussum/homepage/domain/post/service/factory/GeneralBoardImpl.java
  src/main/java/ussum/homepage/domain/post/service/factory/NoticeBoardImpl.java
  src/main/java/ussum/homepage/infra/jpa/comment/PostCommentMapper.java
  src/main/java/ussum/homepage/infra/jpa/comment/PostCommentRepositoryImpl.java
  src/main/java/ussum/homepage/infra/jpa/comment/PostReplyCommentMapper.java
  src/main/java/ussum/homepage/infra/jpa/comment/PostReplyCommentRepositoryImpl.java
  src/main/java/ussum/homepage/infra/jpa/comment/entity/PostCommentEntity.java
  src/main/java/ussum/homepage/infra/jpa/comment/entity/PostReplyCommentEntity.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/Category.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/OngoingStatus.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/PostEntity.java
Labels: refactor, feature, fix

#70 [refactor] #50 api 테스트 중 오류해결, 파라미터 수정 및 dto 수정
  src/main/java/ussum/homepage/application/post/controller/PostManageController.java
  src/main/java/ussum/homepage/application/post/service/PostManageService.java
  src/main/java/ussum/homepage/application/post/service/dto/request/PostCreateRequest.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postList/NoticePostResponse.java
  src/main/java/ussum/homepage/domain/post/Post.java
  src/main/java/ussum/homepage/domain/post/PostRepository.java
  src/main/java/ussum/homepage/domain/post/service/PostReader.java
  src/main/java/ussum/homepage/domain/post/service/factory/BoardImpl.java
  src/main/java/ussum/homepage/domain/post/service/factory/GeneralBoardImpl.java
  src/main/java/ussum/homepage/domain/post/service/factory/NoticeBoardImpl.java
  src/main/java/ussum/homepage/global/config/CorsConfig.java
  src/main/java/ussum/homepage/global/config/SecurityConfig.java
  src/main/java/ussum/homepage/global/error/status/ErrorStatus.java
  src/main/java/ussum/homepage/infra/jpa/group/entity/GroupCode.java
  src/main/java/ussum/homepage/infra/jpa/member/entity/MemberCode.java
  src/main/java/ussum/homepage/infra/jpa/post/PostRepositoryImpl.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/Category.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/OngoingStatus.java
  src/main/java/ussum/homepage/infra/utils/DateUtils.java
Labels: refactor

#71 [feat] #69 공지사항 게시물 작성 시 로그인한 계정에 따라 카테고리 분류
  src/main/java/ussum/homepage/application/post/service/PostManageService.java
  src/main/java/ussum/homepage/application/post/service/dto/response/SimplePostResponse.java
  src/main/java/ussum/homepage/domain/post/Post.java
  src/main/java/ussum/homepage/domain/post/service/PostStatusProcessor.java
  src/main/java/ussum/homepage/global/config/SecurityConfig.java
  src/main/java/ussum/homepage/infra/jpa/member/entity/MemberCode.java
  src/main/java/ussum/homepage/infra/jpa/post/PostRepositoryImpl.java
  src/main/java/ussum/homepage/infra/utils/DateUtils.java
Labels: refactor, feature

#72 [refactor] #50 category로 필터링 로직 추가 및 dto 필드 수정
  src/main/java/ussum/homepage/application/post/controller/PostManageController.java
  src/main/java/ussum/homepage/application/post/service/PostManageService.java
  src/main/java/ussum/homepage/application/post/service/dto/response/DataPostResponse.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postList/AuditPostResponseDto.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postList/LostPostResponse.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postList/NoticePostResponse.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postList/PartnerPostResponse.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postList/PetitionPostResponse.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postList/PostListResDto.java
  src/main/java/ussum/homepage/domain/post/PostRepository.java
  src/main/java/ussum/homepage/domain/post/service/PostReader.java
  src/main/java/ussum/homepage/domain/post/service/factory/BoardImpl.java
  src/main/java/ussum/homepage/domain/post/service/factory/GeneralBoardImpl.java
  src/main/java/ussum/homepage/domain/post/service/factory/NoticeBoardImpl.java
  src/main/java/ussum/homepage/infra/jpa/post/PostRepositoryImpl.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/Category.java
Labels: refactor

#73 [feat] : 학생자치기구 로그인 및 회원가입, 자잘한 로직 수정
  src/main/java/ussum/homepage/application/admin/controller/AdminController.java
  src/main/java/ussum/homepage/application/admin/service/AdminService.java
  src/main/java/ussum/homepage/application/admin/service/dto/request/CouncilSignInRequest.java
  src/main/java/ussum/homepage/application/post/controller/PostManageController.java
  src/main/java/ussum/homepage/application/post/service/PostManageService.java
  src/main/java/ussum/homepage/application/user/controller/OAuthController.java
  src/main/java/ussum/homepage/application/user/controller/OnBoardingController.java
  src/main/java/ussum/homepage/application/user/service/OAuthService.java
  src/main/java/ussum/homepage/application/user/service/OnBoardingService.java
  src/main/java/ussum/homepage/application/user/service/dto/request/CouncilLoginRequest.java
  src/main/java/ussum/homepage/application/user/service/dto/request/UserRequest.java
  src/main/java/ussum/homepage/application/user/service/dto/response/CouncilLoginResponse.java
  src/main/java/ussum/homepage/domain/user/User.java
  src/main/java/ussum/homepage/domain/user/UserRepository.java
  src/main/java/ussum/homepage/domain/user/service/UserManager.java
  src/main/java/ussum/homepage/domain/user/service/UserModifier.java
  src/main/java/ussum/homepage/domain/user/service/UserReader.java
  src/main/java/ussum/homepage/global/config/SecurityConfig.java
  src/main/java/ussum/homepage/global/error/status/ErrorStatus.java
  src/main/java/ussum/homepage/infra/jpa/user/UserMapper.java
  src/main/java/ussum/homepage/infra/jpa/user/UserRepositoryImpl.java
  src/main/java/ussum/homepage/infra/jpa/user/entity/UserEntity.java
  src/main/java/ussum/homepage/infra/jpa/user/repository/UserJpaRepository.java
  src/main/java/ussum/homepage/infra/utils/S3utils.java
Labels: feature, fix

#74 [fix] : postFile api 파라미터 required false
  src/main/generated/ussum/homepage/infra/jpa/user/entity/QUserEntity.java
  src/main/java/ussum/homepage/application/post/controller/PostManageController.java
Labels: fix

#76 [refactor] #75 청원게시물 전체 조회 시 진행상태 변경 로직 추가
  src/main/java/ussum/homepage/application/post/service/PostManageService.java
  src/main/java/ussum/homepage/domain/post/service/PostStatusProcessor.java
  src/main/java/ussum/homepage/infra/jpa/post/PostMapper.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/OngoingStatus.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/PostEntity.java
Labels: refactor

#77 [refactor] #50 자료집 게시판 dto 수정
  src/main/java/ussum/homepage/application/post/service/PostManageService.java
  src/main/java/ussum/homepage/application/post/service/dto/response/DataPostResponse.java
  src/main/java/ussum/homepage/domain/comment/service/formatter/QuadFunction.java
Labels: refactor

#79 [fix] #78 게시물 삭제 시 연관된 파일 삭제 안되는 문제 해결
  src/main/java/ussum/homepage/application/post/controller/PostController.java
  src/main/java/ussum/homepage/application/post/controller/PostManageController.java
  src/main/java/ussum/homepage/application/post/service/PostManageService.java
  src/main/java/ussum/homepage/infra/jpa/post/PostRepositoryImpl.java
Labels: bug

#81 [refactor] #50 fileCategory null 처리
  src/main/java/ussum/homepage/infra/jpa/post/PostFileMapper.java
Labels: refactor

#82 [fix] 파일,이미지 변수에 s 추가
  src/main/java/ussum/homepage/domain/post/service/PostFileReader.java
Labels: fix

#83 [refactor] 게시물 content 필드 Lob 추가
  src/main/java/ussum/homepage/HomepageApplication.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/PostEntity.java
Labels: refactor

#85 [fix] 인기청원 게시물 좋아요 순으로 반환 안되는 문제 해결
  src/main/java/ussum/homepage/infra/jpa/post/PostRepositoryImpl.java
Labels: fix

#86 [refactor] #78 청원게시물 상태 변경 스케줄러 및 트리거 형식으로 수정 및 OnGoingStatus 이용 X(Category와 중복)
  build.gradle
  src/main/java/ussum/homepage/application/comment/service/CommentService.java
  src/main/java/ussum/homepage/application/post/service/PostManageService.java
  src/main/java/ussum/homepage/application/post/service/PostService.java
  src/main/java/ussum/homepage/application/post/service/dto/request/PostCreateRequest.java
  src/main/java/ussum/homepage/application/post/service/dto/request/PostUpdateRequest.java
  src/main/java/ussum/homepage/application/post/service/dto/response/SimplePostResponse.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postDetail/PetitionPostDetailResponse.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postList/NoticePostResponse.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postList/PetitionPostResponse.java
  src/main/java/ussum/homepage/application/reaction/controller/PostReactionController.java
  src/main/java/ussum/homepage/application/reaction/service/PostReactionService.java
  src/main/java/ussum/homepage/domain/post/Post.java
  src/main/java/ussum/homepage/domain/post/PostRepository.java
  src/main/java/ussum/homepage/domain/post/service/PetitionPostProcessor.java
  src/main/java/ussum/homepage/domain/post/service/PostStatusProcessor.java
  src/main/java/ussum/homepage/infra/jpa/post/PostMapper.java
  src/main/java/ussum/homepage/infra/jpa/post/PostRepositoryImpl.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/Category.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/OngoingStatus.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/PostEntity.java
  src/test/java/ussum/homepage/domain/post/service/PetitionPostProcessorTest.java
Labels: refactor

#87 [feat] : S3 객체 삭제 처리 수정
  src/main/java/ussum/homepage/application/post/service/PostManageService.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postSave/PostFileDeleteResponse.java
  src/main/java/ussum/homepage/infra/utils/S3utils.java
Labels: fix

#88 [fix] : 학생회 회원가입, 게시물 수정
  src/main/java/ussum/homepage/application/admin/service/AdminService.java
  src/main/java/ussum/homepage/application/post/service/dto/request/PostUpdateRequest.java
  src/main/java/ussum/homepage/infra/jpa/member/MemberMapper.java
Labels: fix

#89 [fix] : PostUpdateRequest 수정
  src/main/java/ussum/homepage/application/post/service/dto/request/PostUpdateRequest.java
Labels: fix

#90 [fix, refactor] : PostFile API 수정, 온보딩 로직 수정
  src/main/generated/ussum/homepage/infra/jpa/comment/entity/QPostCommentEntity.java
  src/main/generated/ussum/homepage/infra/jpa/comment/entity/QPostReplyCommentEntity.java
  src/main/generated/ussum/homepage/infra/jpa/post/entity/QPostEntity.java
  src/main/java/ussum/homepage/application/post/service/PostManageService.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postSave/PostFileMediatorResponse.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postSave/PostFileResponse.java
  src/main/java/ussum/homepage/application/user/service/OnBoardingService.java
  src/main/java/ussum/homepage/application/user/service/dto/response/CouncilLoginResponse.java
  src/main/java/ussum/homepage/infra/jpa/member/repository/MemberJpaRepository.java
  src/main/java/ussum/homepage/infra/utils/S3utils.java
Labels: refactor, fix

#92 [fix] : 온보딩 if문 수정
  src/main/java/ussum/homepage/domain/csv_user/service/StudentCsvReader.java
Labels: fix

#93 [fix] : 자료형 불일치 문제 해결
  src/main/java/ussum/homepage/domain/csv_user/service/StudentCsvReader.java
Labels: fix

#97 [feat] : #96 해당 사용자가 좋아요를 눌렀는지 확인 여부 필드 추가
  src/main/java/ussum/homepage/application/comment/service/PostCommentManageService.java
  src/main/java/ussum/homepage/application/comment/service/dto/response/PostCommentResponse.java
  src/main/java/ussum/homepage/application/comment/service/dto/response/PostReplyCommentResponse.java
  src/main/java/ussum/homepage/application/post/service/PostManageService.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postDetail/PetitionPostDetailResponse.java
  src/main/java/ussum/homepage/application/reaction/service/PostCommentReactionService.java
  src/main/java/ussum/homepage/application/reaction/service/PostReactionService.java
  src/main/java/ussum/homepage/domain/comment/service/formatter/PostCommentFormatter.java
  src/main/java/ussum/homepage/domain/comment/service/formatter/PostReplyCommentFormatter.java
  src/main/java/ussum/homepage/domain/post/service/formatter/PostDetailFunction.java
  src/main/java/ussum/homepage/domain/postlike/PostReactionRepository.java
  src/main/java/ussum/homepage/domain/postlike/service/PostReactionManager.java
  src/main/java/ussum/homepage/domain/postlike/service/PostReactionReader.java
  src/main/java/ussum/homepage/domain/reaction/PostCommentReactionRepository.java
  src/main/java/ussum/homepage/domain/reaction/PostReplyCommentReactionRepository.java
  src/main/java/ussum/homepage/domain/reaction/service/PostCommentReactionManager.java
  src/main/java/ussum/homepage/domain/reaction/service/PostCommentReactionReader.java
  src/main/java/ussum/homepage/domain/reaction/service/PostReplyCommentReactionManager.java
  src/main/java/ussum/homepage/infra/jpa/postlike/PostReactionRepositoryImpl.java
  src/main/java/ussum/homepage/infra/jpa/postlike/repository/PostReactionJpaRepository.java
  src/main/java/ussum/homepage/infra/jpa/reaction/PostCommentReactionRepositoryImpl.java
  src/main/java/ussum/homepage/infra/jpa/reaction/PostReplyCommentReactionRepositoryImpl.java
  src/main/java/ussum/homepage/infra/jpa/reaction/repository/PostCommentReactionJpaRepository.java
  src/main/java/ussum/homepage/infra/jpa/reaction/repository/PostReplyCommentReactionJpaRepository.java
Labels: feature

#99 [refactor] #98 게시글 리스트 조회 factory 패턴으로 리팩토링
  src/main/java/ussum/homepage/application/post/service/PostManageService.java
  src/main/java/ussum/homepage/domain/post/service/factory/postList/AuditPostResponseFactory.java
  src/main/java/ussum/homepage/domain/post/service/factory/postList/DataPostResponseFactory.java
  src/main/java/ussum/homepage/domain/post/service/factory/postList/LostPostResponseFactory.java
  src/main/java/ussum/homepage/domain/post/service/factory/postList/NoticePostResponseFactory.java
  src/main/java/ussum/homepage/domain/post/service/factory/postList/PartnerPostResponseFactory.java
  src/main/java/ussum/homepage/domain/post/service/factory/postList/PetitionPostResponseFactory.java
  src/main/java/ussum/homepage/domain/post/service/factory/postList/PostListResponseFactory.java
  src/main/java/ussum/homepage/domain/post/service/factory/postList/PostResponseFactoryProvider.java
  src/test/java/ussum/homepage/application/post/service/PostManageServiceTest.java
Labels: refactor

#100 [feat] : Code Enum 한글 반환 처리
  src/main/java/ussum/homepage/infra/jpa/group/GroupMapper.java
  src/main/java/ussum/homepage/infra/jpa/group/entity/GroupCode.java
  src/main/java/ussum/homepage/infra/jpa/member/MemberMapper.java
  src/main/java/ussum/homepage/infra/jpa/member/entity/MajorCode.java
  src/main/java/ussum/homepage/infra/jpa/member/entity/MemberCode.java
Labels: feature

#101 [fix, hotfix] : 자치기구 로그인 수정, 게시물 수정 api
  src/main/java/ussum/homepage/application/post/service/PostManageService.java
  src/main/java/ussum/homepage/application/post/service/dto/request/PostUpdateRequest.java
  src/main/java/ussum/homepage/application/user/service/OAuthService.java
  src/main/java/ussum/homepage/application/user/service/dto/response/CouncilLoginResponse.java
  src/main/java/ussum/homepage/domain/member/service/MemberReader.java
Labels: fix

#102 [feat] : 자치기구 회원가입 수정
  src/main/java/ussum/homepage/application/admin/service/AdminService.java
  src/main/java/ussum/homepage/application/admin/service/dto/request/CouncilSignInRequest.java
  src/main/java/ussum/homepage/domain/group/GroupRepository.java
  src/main/java/ussum/homepage/domain/group/service/GroupReader.java
  src/main/java/ussum/homepage/domain/member/service/MemberAppender.java
  src/main/java/ussum/homepage/domain/user/User.java
  src/main/java/ussum/homepage/infra/jpa/group/GroupRepositoryImpl.java
Labels: feature, fix

#106 [fix] 자료집 조회 dto 수정
  src/main/java/ussum/homepage/application/post/service/dto/response/DataPostResponse.java
  src/main/java/ussum/homepage/application/post/service/dto/response/FileResponse.java
  src/main/java/ussum/homepage/domain/post/service/factory/postList/DataPostResponseFactory.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/PostEntity.java
Labels: fix
