Repository ssu-student-union/homepage-backend, pull requests merged in 2024-10, with the labels that each got.

#124 [fix] : batch 필드명 수정
  src/main/java/ussum/homepage/application/admin/controller/AdminController.java
  src/main/java/ussum/homepage/domain/csv_user/StudentCsv.java
  src/main/java/ussum/homepage/infra/csvBatch/config/FileItemReaderJobConfig.java
  src/main/java/ussum/homepage/infra/csvBatch/csv/CSVReader.java
  src/main/java/ussum/homepage/infra/csvBatch/csv/CSVWriter.java
  src/main/java/ussum/homepage/infra/jpa/csv_user/StudentCsvMapper.java
  src/main/java/ussum/homepage/infra/jpa/csv_user/entity/StudentCsvEntity.java
Labels: fix

#125 [fix] #123 AdminController consume설정
  src/main/java/ussum/homepage/application/admin/controller/AdminController.java
Labels: refactor

#126 [fix] #123 filepath 수정
  src/main/java/ussum/homepage/infra/csvBatch/csv/CSVReader.java
  src/main/java/ussum/homepage/infra/utils/S3utils.java
Labels: fix

#128 [chore] : actuator 의존성 설정
  build.gradle
  src/main/java/ussum/homepage/global/config/SecurityConfig.java
Labels: chore

#129 [fix] batch및 온보딩 오류 수정
  src/main/java/ussum/homepage/domain/csv_user/service/StudentCsvReader.java
  src/main/java/ussum/homepage/infra/csvBatch/config/FileItemReaderJobConfig.java
Labels: fix

#130 [fix] #123 getMajor로 다시 수정
  src/main/java/ussum/homepage/domain/csv_user/service/StudentCsvReader.java
Labels: fix

#132 [hotfix]: 자료집 categort 학부들 추가
  src/main/java/ussum/homepage/infra/jpa/post/entity/FileCategory.java
  src/main/java/ussum/homepage/infra/utils/S3utils.java
Labels: refactor

#135 [add] PASSU 토큰 정보 조회 로직
  src/main/java/ussum/homepage/application/user/controller/UserController.java
  src/main/java/ussum/homepage/application/user/service/UserService.java
  src/main/java/ussum/homepage/application/user/service/dto/request/TokenRequest.java
  src/main/java/ussum/homepage/application/user/service/dto/response/UserInfoResponse.java
  src/main/java/ussum/homepage/domain/csv_user/service/StudentCsvReader.java
  src/main/java/ussum/homepage/global/config/SecurityConfig.java
Labels: feature

#136 [fix] record to class
  src/main/java/ussum/homepage/application/user/controller/UserController.java
  src/main/java/ussum/homepage/application/user/service/dto/request/TokenRequest.java
Labels: fix

#137 [fix] @ResponseBody 삭제
  src/main/java/ussum/homepage/application/user/controller/UserController.java
Labels: fix

#138 [fix] Header로 토큰 입력받는 것으로 수정
  src/main/java/ussum/homepage/application/user/controller/UserController.java
Labels: refactor
