Repository ssu-student-union/homepage-backend, pull requests merged in 2024-09, with the labels that each got.

#109 [refactor, feat] #108 게시물 NEW Status 3일 체크 로직 및 자료집 게시판 검색 api 추가
  src/main/java/ussum/homepage/application/post/controller/PostManageController.java
  src/main/java/ussum/homepage/application/post/service/PostManageService.java
  src/main/java/ussum/homepage/domain/post/PostRepository.java
  src/main/java/ussum/homepage/domain/post/service/PostReader.java
  src/main/java/ussum/homepage/domain/post/service/PostStatusProcessor.java
  src/main/java/ussum/homepage/infra/jpa/post/PostRepositoryImpl.java
Labels: refactor

#114 [feat] #110 비로그인 로그인 모두 허용하는 로직 추가
  src/main/java/ussum/homepage/application/comment/controller/PostCommentManagerController.java
  src/main/java/ussum/homepage/application/post/controller/PostManageController.java
  src/main/java/ussum/homepage/application/post/service/PostManageService.java
  src/main/java/ussum/homepage/global/config/SecurityConfig.java
  src/main/java/ussum/homepage/global/config/auth/UserIdArgumentResolver.java
  src/main/java/ussum/homepage/global/jwt/JwtFilter.java
Labels: feature

#119 [hotfix] #118 댓글목록 조회 시 권한 필드 위치 이동
  src/main/java/ussum/homepage/application/comment/service/PostCommentManageService.java
  src/main/java/ussum/homepage/application/comment/service/dto/response/CommentListResponse.java
  src/main/java/ussum/homepage/application/comment/service/dto/response/PostCommentResponse.java
  src/main/java/ussum/homepage/application/comment/service/dto/response/PostReplyCommentResponse.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postDetail/PostDetailResDto.java
  src/main/java/ussum/homepage/domain/acl/service/post/PostAclAspect.java
  src/main/java/ussum/homepage/domain/acl/service/post/PostAclHandler.java
  src/main/java/ussum/homepage/domain/comment/service/PostCommentReader.java
  src/main/java/ussum/homepage/domain/post/service/PetitionPostProcessor.java
Labels: refactor, fix

#122 [hotfix] update로직
  src/main/generated/ussum/homepage/infra/jpa/acl/entity/QPostAclEntity.java
  src/main/java/ussum/homepage/application/post/service/PostManageService.java
  src/main/java/ussum/homepage/application/post/service/dto/request/PostUpdateRequest.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postList/NoticePostResponse.java
  src/main/java/ussum/homepage/domain/post/service/PostModifier.java
  src/main/java/ussum/homepage/infra/jpa/post/PostMapper.java
  src/main/java/ussum/homepage/infra/jpa/post/PostRepositoryImpl.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/Status.java
Labels: refactor
