Repository ssu-student-union/homepage-backend, pull requests merged in 2024-07, with the labels that each got.

#21 [feat] : #19 onboarding login
  .github/pull_request_template.md
  build.gradle
  src/main/generated/ussum/homepage/infra/jpa/QBaseEntity.java
  src/main/generated/ussum/homepage/infra/jpa/acl/entity/QBoardAclEntity.java
  src/main/generated/ussum/homepage/infra/jpa/acl/entity/QGlobalEntity.java
  src/main/generated/ussum/homepage/infra/jpa/acl/entity/QPostAclEntity.java
  src/main/generated/ussum/homepage/infra/jpa/comment/entity/QPostCommentEntity.java
  src/main/generated/ussum/homepage/infra/jpa/post/entity/QBoardEntity.java
  src/main/generated/ussum/homepage/infra/jpa/post/entity/QCategoryEntity.java
  src/main/generated/ussum/homepage/infra/jpa/post/entity/QPostEntity.java
  src/main/generated/ussum/homepage/infra/jpa/post/entity/QPostFileEntity.java
  src/main/generated/ussum/homepage/infra/jpa/postlike/entity/QPostReactionEntity.java
  src/main/generated/ussum/homepage/infra/jpa/user/entity/QGroupEntity.java
  src/main/generated/ussum/homepage/infra/jpa/user/entity/QMemberEntity.java
  src/main/generated/ussum/homepage/infra/jpa/user/entity/QRoleEntity.java
  src/main/generated/ussum/homepage/infra/jpa/user/entity/QUserEntity.java
  src/main/java/ussum/homepage/application/user/controller/OAuthController.java
  src/main/java/ussum/homepage/application/user/controller/OnBoardingController.java
  src/main/java/ussum/homepage/application/user/controller/UserController.java
  src/main/java/ussum/homepage/application/user/service/OAuthService.java
  src/main/java/ussum/homepage/application/user/service/OnBoardingService.java
  src/main/java/ussum/homepage/application/user/service/UserService.java
  src/main/java/ussum/homepage/application/user/service/dto/request/OnBoardingRequest.java
  src/main/java/ussum/homepage/application/user/service/dto/request/UserRequest.java
  src/main/java/ussum/homepage/application/user/service/dto/response/KakaoTokenResponseDto.java
  src/main/java/ussum/homepage/application/user/service/dto/response/KakaoUserInfoResponseDto.java
  src/main/java/ussum/homepage/application/user/service/dto/response/UserOAuthResponse.java
  src/main/java/ussum/homepage/application/user/service/dto/response/UserResponse.java
  src/main/java/ussum/homepage/domain/user/User.java
  src/main/java/ussum/homepage/domain/user/UserRepository.java
  src/main/java/ussum/homepage/domain/user/auth/KakaoUserInfo.java
  src/main/java/ussum/homepage/domain/user/service/UserAppender.java
  src/main/java/ussum/homepage/domain/user/service/UserModifier.java
  src/main/java/ussum/homepage/domain/user/service/UserReader.java
  src/main/java/ussum/homepage/domain/user/service/formatter/UserFormatter.java
  src/main/java/ussum/homepage/global/config/CorsConfig.java
  src/main/java/ussum/homepage/global/config/SecurityConfig.java
  src/main/java/ussum/homepage/global/error/exception/UnauthorizedException.java
  src/main/java/ussum/homepage/global/error/status/ErrorStatus.java
  src/main/java/ussum/homepage/global/external/oauth/KakaoApiProvider.java
  src/main/java/ussum/homepage/global/jwt/JwtAccessDeniedHandler.java
  src/main/java/ussum/homepage/global/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/ussum/homepage/global/jwt/JwtExceptionFilter.java
  src/main/java/ussum/homepage/global/jwt/JwtFilter.java
  src/main/java/ussum/homepage/global/jwt/JwtProperties.java
  src/main/java/ussum/homepage/global/jwt/JwtTokenInfo.java
  src/main/java/ussum/homepage/global/jwt/JwtTokenProvider.java
  src/main/java/ussum/homepage/infra/config/RedisConfig.java
  src/main/java/ussum/homepage/infra/jpa/comment/repository/PostCommentJpaRepository.java
  src/main/java/ussum/homepage/infra/jpa/user/UserMapper.java
  src/main/java/ussum/homepage/infra/jpa/user/UserRepositoryImpl.java
  src/main/java/ussum/homepage/infra/jpa/user/entity/UserEntity.java
  src/main/java/ussum/homepage/infra/jpa/user/repository/UserJpaRepository.java
Labels: refactor, feature, fix

#27 [fix] postcomment 자잘한 수정 및 postcommentreaction api 구현
  src/main/java/ussum/homepage/application/comment/controller/CommentController.java
  src/main/java/ussum/homepage/application/comment/service/CommentService.java
  src/main/java/ussum/homepage/application/comment/service/dto/PostCommentListResponse.java
  src/main/java/ussum/homepage/application/reaction/controller/PostCommentReactionController.java
  src/main/java/ussum/homepage/application/reaction/service/PostCommentReactionService.java
  src/main/java/ussum/homepage/application/reaction/service/dto/request/PostCommentReactionCreateRequest.java
  src/main/java/ussum/homepage/application/reaction/service/dto/response/PostCommentReactionResponse.java
  src/main/java/ussum/homepage/domain/comment/service/formatter/PostCommentFormatter.java
  src/main/java/ussum/homepage/domain/reaction/PostCommentReaction.java
  src/main/java/ussum/homepage/domain/reaction/PostCommentReactionRepository.java
  src/main/java/ussum/homepage/domain/reaction/exception/PostCommentReactionException.java
  src/main/java/ussum/homepage/domain/reaction/service/PostCommentReactionAppender.java
  src/main/java/ussum/homepage/domain/reaction/service/PostCommentReactionFormatter.java
  src/main/java/ussum/homepage/domain/reaction/service/PostCommentReactionModifier.java
  src/main/java/ussum/homepage/domain/reaction/service/PostCommentReactionReader.java
  src/main/java/ussum/homepage/domain/reaction/service/formatter/PostCommentReactionFormatter.java
  src/main/java/ussum/homepage/global/error/status/ErrorStatus.java
  src/main/java/ussum/homepage/infra/jpa/comment/entity/CommentType.java
  src/main/java/ussum/homepage/infra/jpa/comment/entity/PostCommentEntity.java
  src/main/java/ussum/homepage/infra/jpa/postlike/entity/Reaction.java
  src/main/java/ussum/homepage/infra/jpa/reaction/PostCommentReactionMapper.java
  src/main/java/ussum/homepage/infra/jpa/reaction/PostCommentReactionRepositoryImpl.java
  src/main/java/ussum/homepage/infra/jpa/reaction/entity/PostCommentReactionEntity.java
  src/main/java/ussum/homepage/infra/jpa/reaction/repository/PostCommentReactionJpaRepository.java
Labels: feature, fix

#29 [refactor] response dto PostCommentReaction field 수정 및 likeCount 로직
  src/main/java/ussum/homepage/application/comment/service/dto/PostCommentResponse.java
  src/main/java/ussum/homepage/application/reaction/controller/PostCommentReactionController.java
  src/main/java/ussum/homepage/application/reaction/service/PostCommentReactionService.java
  src/main/java/ussum/homepage/domain/comment/service/formatter/PostCommentFormatter.java
  src/main/java/ussum/homepage/domain/reaction/PostCommentReaction.java
  src/main/java/ussum/homepage/domain/reaction/PostCommentReactionRepository.java
  src/main/java/ussum/homepage/domain/reaction/service/PostCommentReactionManager.java
  src/main/java/ussum/homepage/domain/reaction/service/PostCommentReactionReader.java
  src/main/java/ussum/homepage/infra/jpa/reaction/PostCommentReactionRepositoryImpl.java
  src/main/java/ussum/homepage/infra/jpa/reaction/repository/PostCommentReactionJpaRepository.java
Labels: refactor

#30 [feat] : post reaction api
  src/main/java/ussum/homepage/application/reaction/controller/PostReactionController.java
  src/main/java/ussum/homepage/application/reaction/service/PostCommentReactionService.java
  src/main/java/ussum/homepage/application/reaction/service/PostReactionService.java
  src/main/java/ussum/homepage/application/reaction/service/dto/request/PostReactionCreateRequest.java
  src/main/java/ussum/homepage/application/reaction/service/dto/response/PostReactionResponse.java
  src/main/java/ussum/homepage/domain/post/exception/PostException.java
  src/main/java/ussum/homepage/domain/postlike/PostReaction.java
  src/main/java/ussum/homepage/domain/postlike/PostReactionRepository.java
  src/main/java/ussum/homepage/domain/postlike/service/PostReactionAppender.java
  src/main/java/ussum/homepage/domain/postlike/service/PostReactionFormatter.java
  src/main/java/ussum/homepage/domain/postlike/service/PostReactionManager.java
  src/main/java/ussum/homepage/domain/postlike/service/PostReactionModifier.java
  src/main/java/ussum/homepage/domain/postlike/service/PostReactionReader.java
  src/main/java/ussum/homepage/domain/postlike/service/exception/PostReactionException.java
  src/main/java/ussum/homepage/domain/postlike/service/formatter/PostReactionFormatter.java
  src/main/java/ussum/homepage/domain/reaction/service/PostCommentReactionModifier.java
  src/main/java/ussum/homepage/domain/reaction/service/PostCommentReactionReader.java
  src/main/java/ussum/homepage/global/error/status/ErrorStatus.java
  src/main/java/ussum/homepage/infra/jpa/postlike/PostLikeMapper.java
  src/main/java/ussum/homepage/infra/jpa/postlike/PostReactionMapper.java
  src/main/java/ussum/homepage/infra/jpa/postlike/PostReactionRepositoryImpl.java
  src/main/java/ussum/homepage/infra/jpa/postlike/entity/PostReactionEntity.java
  src/main/java/ussum/homepage/infra/jpa/postlike/repository/PostReactionJpaRepository.java
Labels: feature

#33 [feat] #32 swagger setting
  build.gradle
  src/main/java/ussum/homepage/application/reaction/controller/PostReactionController.java
  src/main/java/ussum/homepage/application/reaction/service/dto/request/PostReactionCreateRequest.java
  src/main/java/ussum/homepage/global/config/SecurityConfig.java
  src/main/java/ussum/homepage/infra/config/SwaggerConfig.java
Labels: feature

#37 [refactor] #34 Transaction layer 변경 및 Post updatedAt, lastEditedAt 구분 완료
  src/main/java/ussum/homepage/application/comment/service/CommentService.java
  src/main/java/ussum/homepage/application/comment/service/dto/request/PostCommentUpdateRequest.java
  src/main/java/ussum/homepage/application/post/service/dto/request/PostCreateRequest.java
  src/main/java/ussum/homepage/application/post/service/dto/request/PostUpdateRequest.java
  src/main/java/ussum/homepage/application/reaction/controller/PostCommentReactionController.java
  src/main/java/ussum/homepage/application/reaction/service/PostCommentReactionService.java
  src/main/java/ussum/homepage/application/reaction/service/PostReactionService.java
  src/main/java/ussum/homepage/domain/comment/service/PostCommentAppender.java
  src/main/java/ussum/homepage/domain/post/Post.java
  src/main/java/ussum/homepage/domain/reaction/service/PostCommentReactionAppender.java
  src/main/java/ussum/homepage/domain/reaction/service/PostCommentReactionModifier.java
  src/main/java/ussum/homepage/infra/jpa/comment/PostCommentMapper.java
  src/main/java/ussum/homepage/infra/jpa/comment/PostCommentRepositoryImpl.java
  src/main/java/ussum/homepage/infra/jpa/comment/entity/PostCommentEntity.java
  src/main/java/ussum/homepage/infra/jpa/post/PostMapper.java
  src/main/java/ussum/homepage/infra/jpa/post/PostRepositoryImpl.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/PostEntity.java
  src/main/java/ussum/homepage/infra/jpa/post/repository/PostJpaRepository.java
Labels: refactor

#39 [refactor] #38 MajorCode Enum 값 추가
  src/main/java/ussum/homepage/application/reaction/controller/PostReactionController.java
  src/main/java/ussum/homepage/infra/jpa/user/entity/MajorCode.java
Labels: refactor
