Repository ssu-student-union/homepage-backend, pull requests merged in 2024-11, with the labels that each got.

#140 [chore]: #139 운영,개발 서버 및 DB분리
  .github/workflows/develop-cicd.yml
  .github/workflows/main-cicd.yml
Labels: chore

#141 Feat/131 infra
  src/main/java/ussum/homepage/application/post/controller/PostController.java
  src/main/java/ussum/homepage/application/post/controller/PostManageController.java
  src/main/java/ussum/homepage/application/post/service/PostManageService.java
  src/main/java/ussum/homepage/application/post/service/PostService.java
  src/main/java/ussum/homepage/application/post/service/dto/request/GeneralPostCreateRequest.java
  src/main/java/ussum/homepage/application/post/service/dto/request/PostCreateRequest.java
  src/main/java/ussum/homepage/application/post/service/dto/request/RigthPostCreateRequest.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postDetail/RightsPostDetailResponse.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postDetail/SuggestionPostDetailResponse.java
  src/main/java/ussum/homepage/domain/post/service/factory/PostFactory.java
  src/main/java/ussum/homepage/domain/post/service/factory/PostFactoryImpl.java
  src/main/java/ussum/homepage/global/config/SecurityConfig.java
  src/main/java/ussum/homepage/global/external/oauth/KakaoApiProvider.java
  src/main/java/ussum/homepage/infra/jpa/post/BoardRepositoryImpl.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/BoardCode.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/RightsDetailEntity.java
  src/test/java/ussum/homepage/application/post/service/PostManageServiceTest.java
Labels: refactor, feature

#143 Feat/142 post
  src/main/java/ussum/homepage/application/post/controller/PostManageController.java
  src/main/java/ussum/homepage/application/post/service/PostManageService.java
  src/main/java/ussum/homepage/application/post/service/dto/request/GeneralPostCreateRequest.java
  src/main/java/ussum/homepage/application/post/service/dto/request/PostCreateRequest.java
  src/main/java/ussum/homepage/application/post/service/dto/request/RightsDetailRequest.java
  src/main/java/ussum/homepage/application/post/service/dto/request/RightsPostCreateRequest.java
  src/main/java/ussum/homepage/domain/post/RightsDetail.java
  src/main/java/ussum/homepage/domain/post/RightsDetailRepository.java
  src/main/java/ussum/homepage/domain/post/service/PostAdditionalAppender.java
  src/main/java/ussum/homepage/domain/post/service/PostModifier.java
  src/main/java/ussum/homepage/domain/post/service/factory/PostFactoryImpl.java
  src/main/java/ussum/homepage/global/config/BoardRequestBodyArgumentResolver.java
  src/main/java/ussum/homepage/global/config/WebConfig.java
  src/main/java/ussum/homepage/global/config/custom/BoardRequestBody.java
  src/main/java/ussum/homepage/global/error/status/ErrorStatus.java
  src/main/java/ussum/homepage/infra/config/SwaggerConfig.java
  src/main/java/ussum/homepage/infra/jpa/post/RightsDetailMapper.java
  src/main/java/ussum/homepage/infra/jpa/post/RightsDetailRepositoryImpl.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/Category.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/RightsDetailEntity.java
  src/main/java/ussum/homepage/infra/jpa/post/repository/RightsDetailJpaRepository.java
Labels: doc s, fix

#144 Feat/142 post
  src/main/java/ussum/homepage/application/comment/service/CommentService.java
  src/main/java/ussum/homepage/application/post/controller/PostManageController.java
  src/main/java/ussum/homepage/application/post/service/PostManageService.java
  src/main/java/ussum/homepage/application/post/service/dto/request/RightsDetailRequest.java
  src/main/java/ussum/homepage/application/post/service/dto/request/RightsPostCreateRequest.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postDetail/RightsPostDetailResponse.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postDetail/SuggestionPostDetailResponse.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postList/RightsPostResponse.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postList/SuggestionPostResponse.java
  src/main/java/ussum/homepage/domain/acl/service/post/PostAclHandler.java
  src/main/java/ussum/homepage/domain/member/MemberRepository.java
  src/main/java/ussum/homepage/domain/member/service/MemberManager.java
  src/main/java/ussum/homepage/domain/post/RightsDetail.java
  src/main/java/ussum/homepage/domain/post/RightsDetailRepository.java
  src/main/java/ussum/homepage/domain/post/service/PostAdditionalReader.java
  src/main/java/ussum/homepage/domain/post/service/factory/postList/PostResponseFactoryProvider.java
  src/main/java/ussum/homepage/domain/post/service/factory/postList/RightsPostResponseFactory.java
  src/main/java/ussum/homepage/domain/post/service/factory/postList/SuggestionPostResponseFactory.java
  src/main/java/ussum/homepage/domain/post/service/formatter/PostDetailFunction.java
  src/main/java/ussum/homepage/infra/jpa/acl/entity/Action.java
  src/main/java/ussum/homepage/infra/jpa/acl/entity/TargetGroup.java
  src/main/java/ussum/homepage/infra/jpa/member/MemberRepositoryImpl.java
  src/main/java/ussum/homepage/infra/jpa/member/entity/MemberCode.java
  src/main/java/ussum/homepage/infra/jpa/post/RightsDetailMapper.java
  src/main/java/ussum/homepage/infra/jpa/post/RightsDetailRepositoryImpl.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/Category.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/RightsDetailEntity.java
  src/main/java/ussum/homepage/infra/jpa/post/repository/RightsDetailJpaRepository.java
Labels: refactor, feature, fix

#146 [fix] 문예창작전공, 영화예술전공 예외처리
  src/main/java/ussum/homepage/domain/csv_user/service/StudentCsvReader.java
Labels: fix

#147 Feat/142 post
  src/main/java/ussum/homepage/application/comment/service/CommentService.java
  src/main/java/ussum/homepage/application/post/service/PostManageService.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postDetail/SuggestionPostDetailResponse.java
  src/main/java/ussum/homepage/application/reaction/service/PostReactionService.java
  src/main/java/ussum/homepage/domain/member/MemberRepository.java
  src/main/java/ussum/homepage/domain/member/service/MemberManager.java
  src/main/java/ussum/homepage/domain/post/service/PostAdditionalReader.java
  src/main/java/ussum/homepage/domain/post/service/factory/PostFactory.java
  src/main/java/ussum/homepage/domain/post/service/factory/PostProcessorFactory.java
  src/main/java/ussum/homepage/domain/post/service/processor/BasePostProcessor.java
  src/main/java/ussum/homepage/domain/post/service/processor/PetitionPostProcessor.java
  src/main/java/ussum/homepage/domain/post/service/processor/PostProcessor.java
  src/main/java/ussum/homepage/domain/post/service/processor/SuggestionPostProcessor.java
  src/main/java/ussum/homepage/infra/jpa/member/MemberRepositoryImpl.java
  src/main/java/ussum/homepage/infra/jpa/member/entity/MemberCode.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/BoardCode.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/RightsDetailEntity.java
Labels: refactor, feature, fix

#148 Feat/142 post
  src/main/java/ussum/homepage/application/post/service/PostManageService.java
  src/main/java/ussum/homepage/application/post/service/dto/request/GeneralPostCreateRequest.java
  src/main/java/ussum/homepage/application/post/service/dto/request/PostCreateRequest.java
  src/main/java/ussum/homepage/application/post/service/dto/request/RightsPostCreateRequest.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postDetail/RightsPostDetailResponse.java
  src/main/java/ussum/homepage/application/post/service/dto/response/postList/RightsPostResponse.java
  src/main/java/ussum/homepage/domain/post/service/PostAdditionalAppender.java
  src/main/java/ussum/homepage/domain/post/service/factory/PostFactoryImpl.java
Labels: fix

#150 [fix] :#142 SuggestionTarget null 이슈 해결
  src/main/java/ussum/homepage/infra/jpa/post/PostMapper.java
  src/main/java/ussum/homepage/infra/jpa/post/entity/SuggestionTarget.java
Labels: bug

#153 [refactor]: #152 개발 도메인 CORS 설정
  src/main/java/ussum/homepage/global/config/CorsConfig.java
Labels: feature
